apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nursultannd/frontend:3
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://api.sa.homework"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ser
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
